#pragma config(Sensor, in1,    armSensor,      sensorPotentiometer)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pid.c"

task main() {
	const float Kp = 0.05;
  const float Ki = 0.01;
  const float Kd = 1;

  const int hz = 20;
  const int dt = 1000/hz;

  const int integralThreshold = 150;

	PidState state;

  pidInitState(state, Kp, Ki, Kd, integralThreshold);

  pidSetTarget(state, SensorValue[armSensor]);

  while(true) {
    int output = pid(state, SensorValue[armSensor], dt);
    motor[armMotor] = output;

    wait1Msec(dt);
  }
}
