#pragma config(Sensor, in1,    liftPotLeft,    sensorPotentiometer)
#pragma config(Sensor, in2,    liftPotRight,   sensorPotentiometer)
#pragma config(Sensor, in5,    autonomousSwitch, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveEncFrontLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  driveEncBackLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  driveEncBackRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  driveEncFrontRight, sensorQuadEncoder)
#pragma config(Motor,  port1,           driveBackLeft, tmotorVex393, openLoop, encoder, encoderPort, dgtl5, 1000)
#pragma config(Motor,  port2,           liftLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           driveFrontLeft, tmotorVex269, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port5,           driveFrontRight, tmotorVex269, openLoop, reversed, encoder, encoderPort, dgtl9, 1000)
#pragma config(Motor,  port6,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           intakeRight,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           liftRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          driveBackRight, tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl7, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"
#include "common.c"
#include "liftcontrol.c"
#include "intakecontrol.c"
#include "drivecontrol.c"

// Forward Declarations
void resetSensors();
void resetMotors();

int LIFT_SPEED = 17;


/////////////////////////////////////////////////////////////////////////////////////////
//                           Pre-Autonomous Function
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton() {
  bStopTasksBetweenModes = true;

  resetSensors();

  lift_init();
}


/////////////////////////////////////////////////////////////////////////////////////////
//                                 Autonomous Task
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous() {
	StartTask(lift);
	lift_static_enable(0);

	if (SensorValue[autonomousSwitch] > 2500) { // autonomous potentiometer left
		drive_straight(6, 127);
		drive_straight(-3, 127);
		drive_strafe(10, 100); // strafe right (align with five stack)
		drive_straight(15, 110); // drive straight towards five stack
	  lift_static_enable(LIFT_DOWN_SPEED * 2);
		intake_in();
		// drive straight through five stack (picking up the sacks)
		drive_straight(15, 110);
		drive_straight(-1, 100);drive_straight(4, 110);
		drive_straight(-1, 100);drive_straight(4, 110);
		drive_straight(-1, 100);drive_straight(4, 110);
		drive_straight(-1, 100);drive_straight(4, 110);
		lift_static_disable();
		intake_stop();
		lift_set_target(LIFT_MID); // lift to holding position
		drive_turn(-90, 100);
		drive_straight(35, 127);
		while (!lift_at_target(100));
		drive_turn(90, 100);
		lift_set_target(LIFT_SCORING);
		drive_straight(35, 127);
		while (!lift_at_target(100));
		intake_out(); // score the sacks
		wait1Msec(2000);
		intake_stop();
		drive_straight(-22, 127); // back up
		lift_set_target(LIFT_MID);
	} else if (SensorValue[autonomousSwitch] < 1500) { // autonomous potentiometer right
		drive_straight(6, 127);
		drive_straight(-3, 127);
		drive_strafe(-10, 100); // strafe left (align with five stack)
		drive_straight(15, 100); // drive straight towards five stack
		lift_static_enable(LIFT_DOWN_SPEED * 2);
		intake_in();
		// drive straight through five stack (picking up the sacks)
		drive_straight(12, 100);
		drive_straight(-1, 100);drive_straight(4, 100);
		drive_straight(-1, 100);drive_straight(4, 100);
		drive_straight(-1, 100);drive_straight(4, 100);
		drive_straight(-1, 100);drive_straight(4, 100);
		lift_static_disable();
		intake_stop();
		lift_set_target(LIFT_MID); // lift to holding position
		while (!lift_at_target(100));
		lift_set_target(LIFT_SCORING);
		drive_straight(35, 90);
		while (!lift_at_target(100));
		intake_out();
		wait1Msec(2000);
		intake_stop();
		drive_straight(-22, 100);
		lift_set_target(LIFT_MID);
	} else { // autonomous potentiometer up
		drive_straight(12, 127);
		drive_straight(4, 127);
		drive_turn(720, 127);
		drive_turn(-360, 127);
	}
}


/////////////////////////////////////////////////////////////////////////////////////////
//                                 User Control Task
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol() {
	lift_init();
	StartTask(lift);

	while (true) {
		while (!vexRT[Btn7R]) {
			if (vexRT[Btn7D]) {
				lift_set_target(1473);
			}

			if (vexRT[Btn7U]) {
			  LIFT_SPEED = 10;
			} else {
				LIFT_SPEED = 20;
			}

			if (vexRT[Btn8U]) {
				lift_static_enable(-100);
		  } else if (vexRT[Btn8D]) {
				lift_static_enable(100);
		  } else {
		    if (lift_static_enabled()) {
		    	lift_set_target(SensorValue[liftPotLeft]);
					lift_static_disable();
				}

				if (vexRT[Btn6U] && vexRT[Btn6D])
					lift_set_target(1473);
	  		else if (vexRT[Btn6U])
					lift_manual(-LIFT_SPEED);
			  else if (vexRT[Btn6D])
			  	lift_manual(LIFT_SPEED);
				else
					lift_manual(0);
			}

			if (vexRT[Btn5U]) {
				motor[intakeLeft] = -100;
				motor[intakeRight] = -100;
			} else if (vexRT[Btn5D]) {
				motor[intakeLeft] = 100;
				motor[intakeRight] = 100;
			} else {
				motor[intakeLeft] = 0;
				motor[intakeRight] = 0;
			}

			drive_manual(vexRT[Ch4], vexRT[Ch3], vexRT[Ch1]);

			wait1Msec(LIFT_DT);
		}

		resetMotors();
		resetSensors();

		wait1Msec(5000);
	}
}

void resetSensors() {
	SensorValue[in1] = 0;
	SensorValue[in2] = 0;
	SensorValue[in3] = 0;
	SensorValue[in4] = 0;
	SensorValue[in5] = 0;
	SensorValue[in6] = 0;
	SensorValue[in7] = 0;
	SensorValue[in8] = 0;

	SensorValue[dgtl1]  = 0;
	SensorValue[dgtl2]  = 0;
	SensorValue[dgtl3]  = 0;
	SensorValue[dgtl4]  = 0;
	SensorValue[dgtl5]  = 0;
	SensorValue[dgtl6]  = 0;
	SensorValue[dgtl7]  = 0;
	SensorValue[dgtl8]  = 0;
	SensorValue[dgtl9]  = 0;
	SensorValue[dgtl10] = 0;
	SensorValue[dgtl11] = 0;
	SensorValue[dgtl12] = 0;
}

void resetMotors() {
	motor[port1]  = 0;
	motor[port2]  = 0;
	motor[port3]  = 0;
	motor[port4]  = 0;
	motor[port5]  = 0;
	motor[port6]  = 0;
	motor[port7]  = 0;
	motor[port8]  = 0;
	motor[port9]  = 0;
	motor[port10] = 0;
}
